// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __LionCorba_hh__
#define __LionCorba_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_LionCorba
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_LionCorba
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_LionCorba
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE LionCobra

_CORBA_MODULE_BEG

  struct Student {
    typedef _CORBA_ConstrType_Variable_Var<Student> _var_type;

    
    ::CORBA::Long studID;

    ::CORBA::String_member name;

    ::CORBA::String_member ssn;

    ::CORBA::String_member emailAddress;

    ::CORBA::String_member homePhone;

    ::CORBA::String_member localAddr;

    ::CORBA::String_member emergencyContact;

    ::CORBA::Long programID;

    ::CORBA::String_member paymentID;

    ::CORBA::Long academicStatus;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Student::_var_type Student_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< Student,Student_var > Student_out;

#ifndef __LionCobra_mStudentDB__
#define __LionCobra_mStudentDB__
  class StudentDB;
  class _objref_StudentDB;
  class _impl_StudentDB;
  
  typedef _objref_StudentDB* StudentDB_ptr;
  typedef StudentDB_ptr StudentDBRef;

  class StudentDB_Helper {
  public:
    typedef StudentDB_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_StudentDB, StudentDB_Helper> StudentDB_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_StudentDB,StudentDB_Helper > StudentDB_out;

#endif

  // interface StudentDB
  class StudentDB {
  public:
    // Declarations for this interface type.
    typedef StudentDB_ptr _ptr_type;
    typedef StudentDB_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_StudentDB :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    Student* addToDB(const ::LionCobra::Student& stu);

    // Constructors
    inline _objref_StudentDB()  { _PR_setobj(0); }  // nil
    _objref_StudentDB(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_StudentDB();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_StudentDB(const _objref_StudentDB&);
    _objref_StudentDB& operator = (const _objref_StudentDB&);
    // not implemented

    friend class StudentDB;
  };

  class _pof_StudentDB : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_StudentDB() : _OMNI_NS(proxyObjectFactory)(StudentDB::_PD_repoId) {}
    virtual ~_pof_StudentDB();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_StudentDB :
    public virtual omniServant
  {
  public:
    virtual ~_impl_StudentDB();

    virtual Student* addToDB(const ::LionCobra::Student& stu) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_LionCobra
_CORBA_MODULE_BEG

  class StudentDB :
    public virtual LionCobra::_impl_StudentDB,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~StudentDB();

    inline ::LionCobra::StudentDB_ptr _this() {
      return (::LionCobra::StudentDB_ptr) _do_this(::LionCobra::StudentDB::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_LionCobra
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
LionCobra::StudentDB::_marshalObjRef(::LionCobra::StudentDB_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_LionCorba
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_LionCorba
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_LionCorba
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_LionCorba
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_LionCorba
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_LionCorba
#endif

#endif  // __LionCorba_hh__

